version: '3.8'

services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      # - .:/home/jovyan/work
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8888"
    depends_on:
      - dbMongo
      - dbMySQL

  dbMongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  dbMySQL:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: M YSQLdatabase
      MYSQL_USER: DBuser
      MYSQL_PASSWORD: password
    volumes:
      - mysqldb-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mongodb-data:
  mysqldb-data: